# MIT License
#
# Copyright (c) 2026 jmfrohs
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from utils import get_test_command, get_install_command

def generate_gitignore(lang):
    ignore = ["node_modules/", "coverage/", ".vscode/", ".DS_Store", "*.log"]
    if lang == "python":
        ignore.extend(["__pycache__/", "*.pyc", "venv/", ".env"])
    return "\n".join(ignore)

def generate_license(license_type, author):
    year = "2026"
    if license_type == "MIT":
        return f"""MIT License

Copyright (c) {year} {author}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
    elif license_type == "Apache-2.0":
        return f"""Copyright {year} {author}

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
    elif license_type == "GPL-3.0":
        return f"""Copyright (C) {year} {author}

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""
    return f"Copyright (c) {year} {author}\n"

def generate_readme(
    project_name,
    lang,
    author,
    description,
    version,
    license_type,
    lang_version,
    test_framework,
    package_manager,
):
    if lang == "html":
        install_cmd = get_install_command(package_manager)
        desc_line = f"\n{description}\n" if description else ""
        return f"""# {project_name}
{desc_line}
> Generated by Project Scaffolding CLI | Author: {author} | Version: {version} | License: {license_type}

## Getting Started

### Prerequisites
- Node.js & {package_manager}

### Installation
```bash
{install_cmd}
```

### Development Server
```bash
{package_manager} run start
```
"""
    lang_ver = lang_version or ("18" if lang == "javascript" else "3.11")
    test_cmd = get_test_command(lang, test_framework, package_manager)
    if lang == "javascript":
        install_cmd = get_install_command(package_manager)
        prereq = f"Node.js {lang_ver} & {package_manager}"
    else:
        install_cmd = "python -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
        prereq = f"Python {lang_ver}+"
    desc_line = f"\n{description}\n" if description else ""
    return f"""# {project_name}
{desc_line}
> Generated by Project Scaffolding CLI | Author: {author} | Version: {version} | License: {license_type}

## Getting Started

### Prerequisites
- {prereq}

### Installation
```bash
{install_cmd}
```

### Running Tests
```bash
{test_cmd}
```
"""

def generate_github_ci(lang, lang_version, test_framework, package_manager):
    if lang == "javascript":
        node_version = lang_version or "18"
        test_cmd = get_test_command(lang, test_framework, package_manager)
        install_cmd = get_install_command(package_manager)
        return f"""name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '{node_version}'
      - run: {install_cmd}
      - run: {test_cmd}
"""
    elif lang == "python":
        py_version = lang_version or "3.11"
        test_cmd = get_test_command(lang, test_framework, None)
        return f"""name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '{py_version}'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: {test_cmd}
"""

def generate_gitlab_ci(lang, lang_version, test_framework, package_manager):
    if lang == "javascript":
        node_version = lang_version or "18"
        test_cmd = get_test_command(lang, test_framework, package_manager)
        install_cmd = get_install_command(package_manager)
        return f"""image: node:{node_version}

stages:
  - test

test:
  stage: test
  script:
    - {install_cmd}
    - {test_cmd}
"""
    elif lang == "python":
        py_version = lang_version or "3.11"
        test_cmd = get_test_command(lang, test_framework, None)
        return f"""image: python:{py_version}

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - {test_cmd}
"""

def generate_dockerfile(lang, lang_version, entry):
    if lang == "javascript":
        node_ver = lang_version or "18"
        return f"""FROM node:{node_ver}-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
CMD ["node", "src/js/{entry}"]
"""
    elif lang == "python":
        py_ver = lang_version or "3.11"
        return f"""FROM python:{py_ver}-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "src/{entry}"]
"""

def generate_dockerignore(lang):
    lines = [".git", ".gitignore", "*.log", ".env", "README.md"]
    if lang == "javascript":
        lines += ["node_modules/", "coverage/"]
    elif lang == "python":
        lines += ["__pycache__/", "*.pyc", "venv/"]
    return "\n".join(lines)

def generate_eslint_config():
    return """{
  "env": {
    "browser": true,
    "es2021": true,
    "node": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "rules": {}
}
"""

def generate_flake8_config():
    return """[flake8]
max-line-length = 88
exclude =
    .git,
    __pycache__,
    venv
"""

def generate_pylint_config():
    return """[MASTER]
ignore=venv

[FORMAT]
max-line-length=88
"""

def generate_prettier_config(indent_size=2):
    import json

    config = {
        "tabWidth": indent_size,
        "semi": True,
        "singleQuote": False,
        "printWidth": 80,
    }
    return json.dumps(config, indent=2) + "\n"
